# Standards: 0.1
---
- name: Fact gitter user
  set_fact:
    gitter_user: "{{ gitter_user | default(homebrew_user) | default(ansible_user_id) }}"
  tags:
    - gitter

- become: "{{ (gitter_user != ansible_user_id) | bool }}"
  become_user: "{{ gitter_user }}"
  block:
    - name: Install required package
      ignore_errors: True
      homebrew_cask:
        name: gitter
        greedy: True
        options: appdir=/Applications
        accept_external_apps: False
        state: upgraded
      tags:
        - gitter

    - name: Remove quarantine flag
      register: gitter_quarantine
      failed_when: gitter_quarantine.rc != 0 and "No such xattr" not in gitter_quarantine.stderr
      changed_when: gitter_quarantine.rc == 0
      command: xattr -d com.apple.quarantine /Applications/Gitter.app
      tags:
        - gitter

    - name: Install pidof package
      homebrew:
        name: pidof
      tags:
        - gitter

    - name: Check program running
      register: gitter_running
      failed_when: False
      changed_when: gitter_running.stdout | length > 0 | bool
      command: pidof Gitter
      tags:
        - gitter

    - name: Fact program running
      set_fact:
        gitter_started: "{{ gitter_running.stdout_lines | length > 0 | bool }}"
      tags:
        - gitter

...
