# Standards: 0.1
---
- name: Kill gitter
  command: killall Gitter
  register: gitter_kill
  failed_when: gitter_kill.rc != 0 and "No matching processes belonging to you were found" not in gitter_kill.stderr
  become: "{{ (gitter_user != ansible_user_id) | bool }}"
  become_user: "{{ gitter_user }}"

- name: Start gitter
  when: gitter_started
  command: open -j /Applications/Gitter.app
  become: "{{ (gitter_user != ansible_user_id) | bool }}"
  become_user: "{{ gitter_user }}"

...
